# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme          = "blowfish"
defaultAppearance    = "dark"     # valid options: light or dark
autoSwitchAppearance = true

enableSearch   = true
enableCodeCopy = true

replyByEmail = false

mainSections = ["posts"]
# robots = ""

disableImageOptimization   = false
disableImageOptimizationMD = false
disableTextInHeader        = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/background.svg"
# defaultFeaturedImage   = "/img/featured.svg"
# defaultSocialImage     = "/img/blowfish.jpg"

highlightCurrentMenuArea      = true
smartTOC                      = true
smartTOCHideUnfocusedChildren = true

[header]
    layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
    showMenu               = true
    showCopyright          = true
    showThemeAttribution   = true
    showAppearanceSwitcher = true
    showScrollToTop        = true

[homepage]
    layout = "background" # valid options: page, profile, hero, card, background, custom
    # homepageImage = "/img/iceland.jpg" # used in: hero, and card
    showRecent             = true
    showRecentItems        = 6
    showMoreLink           = true
    showMoreLinkDest       = "posts"
    cardView               = true
    cardViewScreenWidth    = false
    layoutBackgroundBlur   = true    # only used when layout equals background
    disableHeroImageFilter = false   # only used when layout equals hero

[article]
    showDate              = true
    showViews             = true
    showLikes             = false
    showDateOnlyInArticle = false
    showDateUpdated       = true
    showAuthor            = false
    showAuthorBottom      = true
    showHero              = true
    heroStyle             = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur  = true         # only used when heroStyle equals background
    showBreadcrumbs       = true
    showDraftLabel        = true
    # showEdit = true
    # editURL = "https://github.com/"
    # editAppendPath = true
    seriesOpened        = true
    showHeadingAnchors  = true
    showPagination      = true
    invertPagination    = false
    showReadingTime     = false
    showTableOfContents = true
    showRelatedContent  = true
    relatedContentLimit = 6
    showTaxonomies      = true
    showAuthorsBadges   = true
    showWordCount       = true
    # sharingLinks = [
    #     "linkedin",
    #     "twitter",
    #     "bluesky",
    #     "reddit",
    #     "whatsapp",
    #     "telegram",
    #     "pinterest",
    #     "facebook",
    #     "email",
    # ]
    showComments = true
    showZenMode  = true

[list]
    showHero                    = true
    heroStyle                   = "background" # valid options: basic, big, background, thumbAndBackground
    layoutBackgroundBlur        = true         # only used when heroStyle equals background
    layoutBackgroundHeaderSpace = false
    showBreadcrumbs             = false
    showSummary                 = false
    showViews                   = false
    showLikes                   = false
    showTableOfContents         = true
    showCards                   = true
    orderByWeight               = true
    groupByYear                 = false
    cardView                    = true
    cardViewScreenWidth         = false
    constrainItemsWidth         = false

[sitemap]
    excludedKinds = []

[taxonomy]
    showTermCount       = true
    showHero            = true
    heroStyle           = "background" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs     = false
    showViews           = false
    showLikes           = false
    showTableOfContents = true
    cardView            = false

[term]
    showHero            = true
    heroStyle           = "background" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs     = false
    showViews           = false
    showLikes           = false
    showTableOfContents = true
    groupByYear         = false
    cardView            = true
    cardViewScreenWidth = false

[firebase]
    # apiKey            = ""
    # authDomain        = ""
    # projectId         = ""
    # storageBucket     = ""
    # messagingSenderId = ""
    # appId             = ""
    # measurementId     = ""

[fathomAnalytics]
    # site = "ABC12345"
    # domain = "llama.yoursite.com"

[umamiAnalytics]
    # websiteid = "ABC12345"
    # domain = "llama.yoursite.com"
    # dataDomains = "yoursite.com,yoursite2.com"
    # scriptName = ""
    # enableTrackEvent = false

[selineAnalytics]
    # token = "XXXXXX"
    # enableTrackEvent = false

[buymeacoffee]
    #   identifier = "name"
    #   globalWidget = true
    #   globalWidgetMessage = ""
    #   globalWidgetColor = "#FFDD00"
    #   globalWidgetPosition = "Right"

[verification]
    # google = ""
    # bing = ""
    # pinterest = ""
    # yandex = ""

[rssnext]
    # feedId = ""
    # userId = ""
